version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/mobilizeme.com.au/
hooks:
  AfterInstall:
    - location: scripts/postjob
      timeout: 3000000
      runas: ubuntu
permissions:
  - object: /var/www/mobilizeme.com.au/
    pattern: "**"
    owner: ubuntu
    group: www-data
    mode: 644
    type:
      - file
  - object: /var/www/mobilizeme.com.au/
    pattern: "**"
    owner: ubuntu
    group: www-data
    mode: 755
    type:
      - directory